#ifndef iGameTensorFilter_h
#define iGameTensorFilter_h
/**
 * @class   iGameTensorFilter
 * @brief   iGameTensorFilter's brief
 */

#include "iGameDrawObject.h"
#include "iGameSurfaceMesh.h"
#include "iGameTensorRepresentation.h"
#include "iGameFilter.h"
IGAME_NAMESPACE_BEGIN
class Scene;
class iGameTensorFilter : public Filter {
public:
    I_OBJECT(iGameTensorFilter);
    static iGameTensorFilter* New() { return new iGameTensorFilter; }
    ~iGameTensorFilter();

    //可以单独设置点云数据，无需DataObject
    void SetPoints(Points::Pointer);
    //设置张量场数据
    void SetTensorAttributes(ArrayObject::Pointer);
    //设置图元绘制类型
    void SetGlyphType(iGameTensorRepresentation::DrawType drawType) { this->m_TensorManager->SetDrawType(drawType); }

    //更新图元放缩比例
    void SetGlyphScale(double s);
    //设置图元的绘制精度，Slice越大越精细，内存占用也越高
    void SetSliceNum(int s){this->m_TensorManager->SetSliceNum(s); };
    bool Execute() override;

    DoubleArray::Pointer GenerateVectorField();

protected:
    iGameTensorFilter();
    void UpdateTensorObject();

    //更新图元顶点数据
    void UpdateGlyphDrawPositionData();
    //更新图元绘制面片的索引关系
    void UpdateGlyphDrawIndexData();
    //更新图元属性场
    void UpdateGlyphDrawAttributeSet();

private:
    //The number group in which the tensor is located
    Points::Pointer m_Points;
    //Tensor array
    ArrayObject::Pointer m_TensorAttributes;

    iGameTensorRepresentation::Pointer m_TensorManager;

    //Plot the vertex coordinates of the ellipsoid primitives
    Points::Pointer m_DrawGlyphPoints;
    //Adjacency order of ellipsoidal surfaces
    IdArray::Pointer m_DrawGlyphPointOrders;
    
    AttributeSet::Pointer m_DrawGlyphAttributeSet;
    //Store a feature vector (maximum or minimum) generated by each point for use as a vector output.
    DoubleArray::Pointer m_EigenVector;

    SurfaceMesh::Pointer m_TensorObject = nullptr;
};
IGAME_NAMESPACE_END
#endif