cmake_minimum_required(VERSION 3.8)

add_definitions(/D_USE_MATH_DEFINES)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED TRUE)
project("test")
#set(iGameCore_module_DIR "C:/Program Files (x86)/iGameVis/lib/cmake/iGameCore_module")
set(iGameCore_module_DIR "${CMAKE_CURRENT_SOURCE_DIR}/../install/iGameVis/lib/cmake/iGameCore_module")
find_package(iGameCore_module REQUIRED)
if (MSVC)
    add_compile_options(/utf-8)
endif ()
file(COPY "${CMAKE_BINARY_DIR}/Resources" DESTINATION ${CMAKE_CURRENT_BINARY_DIR})
file(COPY "Models" DESTINATION "${CMAKE_CURRENT_BINARY_DIR}")
add_executable(testSetRenderWindow "${CMAKE_CURRENT_SOURCE_DIR}/Rendering/RenderWindow/SetRenderWindow.cpp")
add_executable(testSetMultiRenderWindow "${CMAKE_CURRENT_SOURCE_DIR}/Rendering/RenderWindow/SetMultiWindow.cpp")
add_executable(testMeshletRendering "${CMAKE_CURRENT_SOURCE_DIR}/Rendering/MeshletRendering.cpp")
add_executable(testResetCameraView "${CMAKE_CURRENT_SOURCE_DIR}/Rendering/ResetCameraView.cpp")
add_executable(testSetCameraView "${CMAKE_CURRENT_SOURCE_DIR}/Rendering/SetCameraView.cpp")
add_executable(testSetLineWidth "${CMAKE_CURRENT_SOURCE_DIR}/Rendering/SetLineWidth.cpp")
add_executable(testSetOrthographicProjection "${CMAKE_CURRENT_SOURCE_DIR}/Rendering/SetOrthographicProjection.cpp")
add_executable(testSetPointSize "${CMAKE_CURRENT_SOURCE_DIR}/Rendering/SetPointSize.cpp")
add_executable(testSetTransparency "${CMAKE_CURRENT_SOURCE_DIR}/Rendering/SetTransparency.cpp")
add_executable(testSetViewStyle "${CMAKE_CURRENT_SOURCE_DIR}/Rendering/SetViewStyle.cpp")
add_executable(testSetScalarField "${CMAKE_CURRENT_SOURCE_DIR}/Rendering/SetScalarField.cpp")
add_executable(testSetVolumeRendering "${CMAKE_CURRENT_SOURCE_DIR}/Rendering/SetVolumeRendering.cpp")
add_executable(testSetRenderingPressure "${CMAKE_CURRENT_SOURCE_DIR}/Rendering/SetRenderingPressure.cpp")

add_executable(testChangeRange "${CMAKE_CURRENT_SOURCE_DIR}/Attribute/TestSubDataRangeChangeAndRecollect.cpp")

add_executable(testVector "${CMAKE_CURRENT_SOURCE_DIR}/Filter/Vector/TestVector.cpp")
add_executable(testTimeVaryingVector "${CMAKE_CURRENT_SOURCE_DIR}/Filter/Vector/TestTimeVaryingVector.cpp")
add_executable(testVectorAllCell "${CMAKE_CURRENT_SOURCE_DIR}/Filter/Vector/TestVectorAllCell.cpp")
add_executable(testVectorCellInRange "${CMAKE_CURRENT_SOURCE_DIR}/Filter/Vector/TestVectorCellInRange.cpp")
add_executable(testVectorEveryNth "${CMAKE_CURRENT_SOURCE_DIR}/Filter/Vector/TestVectorEveryNth.cpp")
add_executable(testVectorSubData "${CMAKE_CURRENT_SOURCE_DIR}/Filter/Vector/TestVectorSubData.cpp")
add_executable(testStreamline "${CMAKE_CURRENT_SOURCE_DIR}/Filter/Vector/TestStreamline.cpp")
add_executable(testTensorView "${CMAKE_CURRENT_SOURCE_DIR}/Filter/Tensor/TestTensorView.cpp")

add_executable(testParallelCoordinatesData "${CMAKE_CURRENT_SOURCE_DIR}/Filter/VisualizationData/TestParallelCoordinatesData.cpp")
add_executable(testVariableCorrelationData "${CMAKE_CURRENT_SOURCE_DIR}/Filter/VisualizationData/TestVariableCorrelationData.cpp")
add_executable(testVariableDensityData "${CMAKE_CURRENT_SOURCE_DIR}/Filter/VisualizationData/TestVariableDensityData.cpp")
add_executable(testPlotLineData "${CMAKE_CURRENT_SOURCE_DIR}/Filter/VisualizationData/TestPlotLineData.cpp")

add_executable(testSetSelectionCallBack "${CMAKE_CURRENT_SOURCE_DIR}/Filter/Selection/TestSetSelectionCallBack.cpp")
add_executable(testSetClearSelectionCallBackFunc "${CMAKE_CURRENT_SOURCE_DIR}/Filter/Selection/TestSetClearSelectionCallBackFunc.cpp")
add_executable(testSetPointsSelect "${CMAKE_CURRENT_SOURCE_DIR}/Filter/Selection/TestSetPointsSelect.cpp")
add_executable(testSetCellsSelect "${CMAKE_CURRENT_SOURCE_DIR}/Filter/Selection/TestSetCellsSelect.cpp")
add_executable(testGetClosestPointsInLine "${CMAKE_CURRENT_SOURCE_DIR}/Filter/Selection/TestGetClosestPointsInLine.cpp")
add_executable(testGetClosestCellsInLine "${CMAKE_CURRENT_SOURCE_DIR}/Filter/Selection/TestGetClosestCellsInLine.cpp")
add_executable(testGetPointsInFrustum "${CMAKE_CURRENT_SOURCE_DIR}/Filter/Selection/TestGetPointsInFrustum.cpp")
add_executable(testGetCellsInFrustum "${CMAKE_CURRENT_SOURCE_DIR}/Filter/Selection/TestGetCellsInFrustum.cpp")

add_executable(testDecoder "${CMAKE_CURRENT_SOURCE_DIR}/Filter/Compression/TestDecoder.cpp")
add_executable(testEncoder "${CMAKE_CURRENT_SOURCE_DIR}/Filter/Compression/TestEncoder.cpp")
add_executable(testSimplification "${CMAKE_CURRENT_SOURCE_DIR}/Filter/Compression/TestSimplification.cpp")

add_executable(testConvertPolyhedralCells "${CMAKE_CURRENT_SOURCE_DIR}/Filter/Convert/TestConvertPolyhedralCells.cpp")
add_executable(testConvertToPointCloud "${CMAKE_CURRENT_SOURCE_DIR}/Filter/Convert/TestConvertToPointCloud.cpp")
add_executable(testConvertToVolumeMesh "${CMAKE_CURRENT_SOURCE_DIR}/Filter/Convert/TestConvertToVolumeMesh.cpp")
add_executable(testConvertToSurfaceMesh "${CMAKE_CURRENT_SOURCE_DIR}/Filter/Convert/TestConvertToSurfaceMesh.cpp")

add_executable(testCGNS "${CMAKE_CURRENT_SOURCE_DIR}/IO/CGNSReader.cpp")
add_executable(testSplineReaderCPU "${CMAKE_CURRENT_SOURCE_DIR}/IO/SplineReaderCPU.cpp")
add_executable(testODBReader "${CMAKE_CURRENT_SOURCE_DIR}/IO/ODBReader.cpp")
add_executable(testNastranReader "${CMAKE_CURRENT_SOURCE_DIR}/IO/NastranReader.cpp")
add_executable(testCASReader "${CMAKE_CURRENT_SOURCE_DIR}/IO/CASReader.cpp")

add_executable(testAnimation "${CMAKE_CURRENT_SOURCE_DIR}/Animation/TestAnimation.cpp")
add_executable(testSaveAnimation "${CMAKE_CURRENT_SOURCE_DIR}/Animation/SaveAnimation.cpp")

add_executable(testClip "${CMAKE_CURRENT_SOURCE_DIR}/Filter/TestClip.cpp")
add_executable(testSlice "${CMAKE_CURRENT_SOURCE_DIR}/Filter/TestSlice.cpp")
add_executable(testDeformation "${CMAKE_CURRENT_SOURCE_DIR}/Filter/TestStressDeformationFilter.cpp")
add_executable(testContourLine "${CMAKE_CURRENT_SOURCE_DIR}/Filter/TestContourLine.cpp")

add_executable(testChangeColorRange "${CMAKE_CURRENT_SOURCE_DIR}/ColorBar/ChangeColorRange.cpp")
add_executable(testChangeColorBar "${CMAKE_CURRENT_SOURCE_DIR}/ColorBar/ChangeColorBar.cpp")

add_executable(testMultiscaleInteraction "${CMAKE_CURRENT_SOURCE_DIR}/MultiscaleInteraction/TestMultiscaleInteraction.cpp")

add_executable(testVortexExtraction "${CMAKE_CURRENT_SOURCE_DIR}/Filter/FeatureExtraction/VortexExtraction.cpp")
add_executable(testCurvatureExtraction "${CMAKE_CURRENT_SOURCE_DIR}/Filter/FeatureExtraction/CurvatureExtraction.cpp")
add_executable(testGradientExtraction "${CMAKE_CURRENT_SOURCE_DIR}/Filter/FeatureExtraction/GradientExtraction.cpp")
add_executable(testLaplacianExtraction "${CMAKE_CURRENT_SOURCE_DIR}/Filter/FeatureExtraction/LaplacianExtraction.cpp")
add_executable(testVortexDetection "${CMAKE_CURRENT_SOURCE_DIR}/Filter/FeatureExtraction/VortexDetection.cpp")

add_executable(testSplineSurfaceReader "${CMAKE_CURRENT_SOURCE_DIR}/IO/SplineSurfaceReader.cpp")
add_executable(testSplineVolumeReader "${CMAKE_CURRENT_SOURCE_DIR}/IO/SplineVolumeReader.cpp")
add_executable(testConvertToLagrangeUnstructuredMesh "${CMAKE_CURRENT_SOURCE_DIR}/Filter/Convert/TestConvertToLagrangeUnstructuredMesh.cpp")

# Link libraries for each target
target_link_libraries(testSetRenderWindow PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testSetMultiRenderWindow PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testMeshletRendering PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testResetCameraView PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testSetCameraView PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testSetLineWidth PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testSetOrthographicProjection PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testSetPointSize PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testSetTransparency PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testSetViewStyle PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testSetScalarField PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testSetVolumeRendering PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testSetRenderingPressure PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})


target_link_libraries(testChangeRange PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})

target_link_libraries(testVector PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testTimeVaryingVector PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testVectorAllCell PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testVectorCellInRange PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testVectorEveryNth PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testVectorSubData PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testStreamline PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testTensorView PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})

target_link_libraries(testParallelCoordinatesData PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testVariableCorrelationData PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testVariableDensityData PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testPlotLineData PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})

target_link_libraries(testSetSelectionCallBack PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testSetClearSelectionCallBackFunc PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testSetPointsSelect PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testSetCellsSelect PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testGetClosestPointsInLine PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testGetClosestCellsInLine PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testGetPointsInFrustum PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testGetCellsInFrustum PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})

target_link_libraries(testDecoder PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testEncoder PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testSimplification PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})

target_link_libraries(testConvertPolyhedralCells PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testConvertToPointCloud PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testConvertToVolumeMesh PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testConvertToSurfaceMesh PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})

target_link_libraries(testAnimation PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testClip PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testSlice PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testDeformation PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testContourLine PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})

target_link_libraries(testSaveAnimation PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testSplineReaderCPU PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testCGNS PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testODBReader PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testNastranReader PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testCASReader PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})

target_link_libraries(testChangeColorRange PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testChangeColorBar PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})

target_link_libraries(testMultiscaleInteraction PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})

target_link_libraries(testVortexExtraction PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testCurvatureExtraction PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testGradientExtraction PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testLaplacianExtraction PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testVortexDetection PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})

target_link_libraries(testSplineSurfaceReader PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testSplineVolumeReader PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})
target_link_libraries(testConvertToLagrangeUnstructuredMesh PUBLIC ${IGAMEVIS_CORE_LIB_TARGETS})

#Use this ThirdParty's Module need to Add Compile Definition
target_compile_definitions(testCGNS PUBLIC CGNS_ENABLE)
target_compile_definitions(testODBReader PUBLIC AbqSDK_ENABLE)
target_compile_definitions(testSaveAnimation PUBLIC FFMPEG_ENABLE)
target_compile_definitions(testSplineSurfaceReader PUBLIC GPSCUDA_ENABLE)
target_compile_definitions(testSplineVolumeReader PUBLIC GPSCUDA_ENABLE)
