#ifndef iGameTensorWidgetBase_h
#define iGameTensorWidgetBase_h
/**
 * @class   iGameTensorWidgetBase
 * @brief   iGameTensorWidgetBase's brief
 */

#include "iGameDrawObject.h"
#include "iGameSurfaceMesh.h"
#include "iGameTensorRepresentation.h"

IGAME_NAMESPACE_BEGIN
class Scene;
class iGameTensorWidgetBase : public DrawObject {
public:
    I_OBJECT(iGameTensorWidgetBase);
    static iGameTensorWidgetBase* New() { return new iGameTensorWidgetBase; }
    ~iGameTensorWidgetBase();

    void SetPoints(Points::Pointer);

    void SetTensorAttributes(ArrayObject::Pointer);

    void ShowTensorField();

    void UpdateGlyphDrawPositionData();
    void UpdateGlyphDrawIndexData();
    void UpdateGlyphDrawColor();
    void UpdateGlyphScale(double s);

    void SetPositionColors(FloatArray::Pointer);

    DoubleArray::Pointer GenerateVectorField();

    Points::Pointer GetDrawGlyphPoints() { return this->m_DrawGlyphPoints; };

    UnsignedIntArray::Pointer GetDrawGlyphPointOrders() {
        return this->m_DrawGlyphPointOrders;
    }

    FloatArray::Pointer GetDrawGlyphColors() { return this->m_DrawGlyphColors; }
    void SetGlyphType(iGameTensorRepresentation::DrawType drawType) {
        this->m_TensorManager->SetDrawType(drawType);
    }

protected:
    iGameTensorWidgetBase();

private:
    //The number group in which the tensor is located
    Points::Pointer m_Points;
    //Tensor array
    ArrayObject::Pointer m_TensorAttributes;

    iGameTensorRepresentation::Pointer m_TensorManager;

    //A color array of the coordinates of an element, generated by the scalar or other method of the vertex at which the element is located
    FloatArray::Pointer m_PositionColors;


    //Plot the vertex coordinates of the ellipsoid primitives
    Points::Pointer m_DrawGlyphPoints;
    //Adjacency order of ellipsoidal surfaces
    UnsignedIntArray::Pointer m_DrawGlyphPointOrders;
    //The color of the ellipsoid
    FloatArray::Pointer m_DrawGlyphColors{FloatArray::New()};
    //Store a feature vector (maximum or minimum) generated by each point for use as a vector output.
    DoubleArray::Pointer m_EigenVector;

public:
    //void Draw(Scene*) override;
    void ConvertToDrawableData() override;
};
IGAME_NAMESPACE_END
#endif