#ifndef iGameTensorBase_h
#define iGameTensorBase_h
/**
 * @class   iGameTensorBase
 * @brief   iGameTensorBase's brief
 */

#include "iGameDrawObject.h"
#include "iGameSurfaceMesh.h"
#include "iGameTensorRepresentation.h"

IGAME_NAMESPACE_BEGIN
class Scene;
class iGameTensorBase : public DrawObject {
public:
    I_OBJECT(iGameTensorBase);
    static iGameTensorBase* New() { return new iGameTensorBase; }
    ~iGameTensorBase();

    void SetPoints(Points::Pointer);
    //设置张量场数据
    void SetTensorAttributes(ArrayObject::Pointer);
    //设置图元绘制类型
    void SetGlyphType(iGameTensorRepresentation::DrawType drawType) { this->m_TensorManager->SetDrawType(drawType); }
    //设置张量场图元颜色，一个position会有一个glyph，颜色是附着在position的，因此每个glyph是纯色
    void SetPositionColors(FloatArray::Pointer);
    //设置张量场图元标量数据，会计算每个position的颜色，并设置图元颜色
    void SetPositionsScalarArray(ArrayObject::Pointer, int d = -1);
    //显示张量场
    void ShowTensorField();

    //更新图元顶点数据
    void UpdateGlyphDrawPositionData();
    //更新图元绘制面片的索引关系
    void UpdateGlyphDrawIndexData();
    //更新图元颜色
    void UpdateGlyphDrawColor();
    //更新图元放缩比例
    void UpdateGlyphScale(double s);


    DoubleArray::Pointer GenerateVectorField();

    Points::Pointer GetDrawGlyphPoints() { return this->m_DrawGlyphPoints; };

    UnsignedIntArray::Pointer GetDrawGlyphPointOrders() { return this->m_DrawGlyphPointOrders; }

    FloatArray::Pointer GetDrawGlyphColors() { return this->m_DrawGlyphColors; }


protected:
    iGameTensorBase();

private:
    //The number group in which the tensor is located
    Points::Pointer m_Points;
    //Tensor array
    ArrayObject::Pointer m_TensorAttributes;

    iGameTensorRepresentation::Pointer m_TensorManager;

    //A color array of the coordinates of an element, generated by the scalar or other method of the vertex at which the element is located
    FloatArray::Pointer m_PositionColors;


    //Plot the vertex coordinates of the ellipsoid primitives
    Points::Pointer m_DrawGlyphPoints;
    //Adjacency order of ellipsoidal surfaces
    UnsignedIntArray::Pointer m_DrawGlyphPointOrders;
    //The color of the ellipsoid
    FloatArray::Pointer m_DrawGlyphColors{FloatArray::New()};
    //Store a feature vector (maximum or minimum) generated by each point for use as a vector output.
    DoubleArray::Pointer m_EigenVector;

public:
    //void Draw(Scene*) override;
    void ConvertToDrawableData() override;
};
IGAME_NAMESPACE_END
#endif