if (NOT IGAME_RUNTIME_DESTINATION)
    message(FATAL_ERROR "IGAME_RUNTIME_DESTINATION is required")
endif ()

file(MAKE_DIRECTORY "${IGAME_RUNTIME_DESTINATION}")

set(_IGAME_RUNTIME_FILES "")

foreach(_IGAME_RUNTIME_DIR IN ITEMS
        "${IGAME_TORCH_RUNTIME_DIR}"
        "${IGAME_TORCH_BIN_DIR}"
        "${IGAME_FFMPEG_RUNTIME_DIR}")
    if (_IGAME_RUNTIME_DIR AND EXISTS "${_IGAME_RUNTIME_DIR}")
        file(GLOB _IGAME_DIRECTORY_DLLS LIST_DIRECTORIES FALSE
                "${_IGAME_RUNTIME_DIR}/*.dll")
        list(APPEND _IGAME_RUNTIME_FILES ${_IGAME_DIRECTORY_DLLS})
    endif ()
endforeach()

if (IGAME_GPS_RUNTIME_DIR AND EXISTS "${IGAME_GPS_RUNTIME_DIR}")
    file(GLOB_RECURSE _IGAME_GPS_DLLS LIST_DIRECTORIES FALSE
            "${IGAME_GPS_RUNTIME_DIR}/*.dll")
    list(APPEND _IGAME_RUNTIME_FILES ${_IGAME_GPS_DLLS})
endif ()

if (IGAME_HDF5_RUNTIME_FILE AND EXISTS "${IGAME_HDF5_RUNTIME_FILE}")
    list(APPEND _IGAME_RUNTIME_FILES "${IGAME_HDF5_RUNTIME_FILE}")
endif ()

if (IGAME_ABQ_RUNTIME_DIR AND IGAME_ABQ_RUNTIME_LIBRARY_NAMES)
    string(REPLACE "," ";" _IGAME_ABQ_RUNTIME_LIBRARY_NAMES
            "${IGAME_ABQ_RUNTIME_LIBRARY_NAMES}")
    foreach(_IGAME_ABQ_LIBRARY_NAME IN LISTS _IGAME_ABQ_RUNTIME_LIBRARY_NAMES)
        set(_IGAME_ABQ_RUNTIME_FILE
                "${IGAME_ABQ_RUNTIME_DIR}/${_IGAME_ABQ_LIBRARY_NAME}.dll")
        if (EXISTS "${_IGAME_ABQ_RUNTIME_FILE}")
            list(APPEND _IGAME_RUNTIME_FILES "${_IGAME_ABQ_RUNTIME_FILE}")
        else ()
            message(WARNING "Example runtime dependency not found: ${_IGAME_ABQ_RUNTIME_FILE}")
        endif ()
    endforeach()
endif ()

list(REMOVE_DUPLICATES _IGAME_RUNTIME_FILES)
if (_IGAME_RUNTIME_FILES)
    file(COPY ${_IGAME_RUNTIME_FILES}
            DESTINATION "${IGAME_RUNTIME_DESTINATION}")
    list(LENGTH _IGAME_RUNTIME_FILES _IGAME_RUNTIME_FILE_COUNT)
    message(STATUS
            "Deployed ${_IGAME_RUNTIME_FILE_COUNT} runtime DLLs to ${IGAME_RUNTIME_DESTINATION}")
endif ()
