#version 450
//#extension GL_ARB_bindless_texture : require

layout (local_size_x = 256) in;

// 0: Determine the visibility of the invisible meshlet in the previous frame in this frame
// 1: Determine the visibility of all meshlets in this frame
uniform int workMode;

// Camera buffer
layout(std140, binding = 0) uniform CameraDataBlock {
    vec3 viewPos;
    int isOrtho;
    vec4 orthoBounds;
    float zNear;
    float zFar;
    mat4 view;
    mat4 proj;
    mat4 proj_view;// proj * view
} cameraData;

// Meshlet Descriptors
struct MeshletDescriptor {
    vec4 spherebounds;
    vec4 extents;
};
layout(std430, binding = 1) buffer MeshletDescriptorBuffer {
    MeshletDescriptor meshletDescs[];
} meshletDescriptorBuffer;

// Indirect command buffer
struct DrawArraysIndirectCommand {
    uint count;
    uint primCount;
    uint first;
    uint baseInstance;
};
layout(std430, binding = 2) buffer ArraysDrawCommandBuffer {
    DrawArraysIndirectCommand commands[];
} arraysDrawCommandBuffer;

struct DrawElementsIndirectCommand {
    uint count;
    uint primCount;
    uint firstIndex;
    uint baseVertex;
    uint baseInstance;
};
layout(std430, binding = 3) buffer ElementsDrawCommandBuffer {
    DrawElementsIndirectCommand commands[];
} elementsDrawCommandBuffer;

// Final visible meshlet info
layout(std430, binding = 4)  buffer VisibleMeshletBuffer{
    uint count;
// uint IDs[];
} visibleMeshletBuffer;

// Final indirect draw command buffer
layout(std430, binding = 5) buffer ArraysFinalDrawCommandBuffer {
    DrawArraysIndirectCommand commands[];
} arraysFinalDrawCommandBuffer;

layout(std430, binding = 6) buffer ElementsFinalDrawCommandBuffer {
    DrawElementsIndirectCommand commands[];
} elementsFinalDrawCommandBuffer;

// Draw Cull Data
layout(std140, binding = 7) uniform CullDataBlock {
    mat4 view_model;
    float P00, P11, zNear, zFar;// symmetric projection parameters
    vec4 frustum;// data for left/right/top/bottom frustum planes
    uint hzbWidth, hzbHeight;// hierarchical z-buffer size in texels
} cullData;

// hierarchical z-buffer
uniform sampler2D hzbSampler;

bool IsVisible(MeshletDescriptor meshletDescriptor);

void main() {
    uint id = gl_GlobalInvocationID.x;
    if (id >= meshletDescriptorBuffer.meshletDescs.length()) {
        return;// Prevent out-of-bounds access
    }

    MeshletDescriptor meshlet = meshletDescriptorBuffer.meshletDescs[id];

    if (workMode == 0) {
        if (elementsDrawCommandBuffer.commands[id].primCount == 0) {
            if (IsVisible(meshlet)) {
                uint oldValue = atomicAdd(visibleMeshletBuffer.count, 1);
                // visibleMeshletBuffer.IDs[oldValue] = id;

                // arrays
                arraysFinalDrawCommandBuffer.commands[oldValue].count = arraysDrawCommandBuffer.commands[id].count;
                arraysFinalDrawCommandBuffer.commands[oldValue].primCount = 1;
                arraysFinalDrawCommandBuffer.commands[oldValue].first = arraysDrawCommandBuffer.commands[id].first;
                arraysFinalDrawCommandBuffer.commands[oldValue].baseInstance = arraysDrawCommandBuffer.commands[id].baseInstance;

                // elements
                elementsFinalDrawCommandBuffer.commands[oldValue].count = elementsDrawCommandBuffer.commands[id].count;
                elementsFinalDrawCommandBuffer.commands[oldValue].primCount = 1;
                elementsFinalDrawCommandBuffer.commands[oldValue].firstIndex = elementsDrawCommandBuffer.commands[id].firstIndex;
                elementsFinalDrawCommandBuffer.commands[oldValue].baseVertex = elementsDrawCommandBuffer.commands[id].baseVertex;
                elementsFinalDrawCommandBuffer.commands[oldValue].baseInstance = elementsDrawCommandBuffer.commands[id].baseInstance;
            }
        }
    } else if (workMode == 1) {
        if (IsVisible(meshlet)) {
            // Write a draw command if the meshlet is visible
            elementsDrawCommandBuffer.commands[id].primCount = 1;
            uint oldValue = atomicAdd(visibleMeshletBuffer.count, 1);
            // visibleMeshletBuffer.IDs[oldValue] = id;

            // arrays
            arraysFinalDrawCommandBuffer.commands[oldValue].count = arraysDrawCommandBuffer.commands[id].count;
            arraysFinalDrawCommandBuffer.commands[oldValue].primCount = 1;
            arraysFinalDrawCommandBuffer.commands[oldValue].first = arraysDrawCommandBuffer.commands[id].first;
            arraysFinalDrawCommandBuffer.commands[oldValue].baseInstance = arraysDrawCommandBuffer.commands[id].baseInstance;

            // elements
            elementsFinalDrawCommandBuffer.commands[oldValue].count = elementsDrawCommandBuffer.commands[id].count;
            elementsFinalDrawCommandBuffer.commands[oldValue].primCount = 1;
            elementsFinalDrawCommandBuffer.commands[oldValue].firstIndex = elementsDrawCommandBuffer.commands[id].firstIndex;
            elementsFinalDrawCommandBuffer.commands[oldValue].baseVertex = elementsDrawCommandBuffer.commands[id].baseVertex;
            elementsFinalDrawCommandBuffer.commands[oldValue].baseInstance = elementsDrawCommandBuffer.commands[id].baseInstance;
        } else {
            // Set draw command count to 0 if the meshlet is not visible
            elementsDrawCommandBuffer.commands[id].primCount = 0;
        }
    }
}

// 2D Polyhedral Bounds of a Clipped, Perspective-Projected 3D Sphere. Michael Mara, Morgan McGuire. 2013
bool ProjectSphere(vec3 C, float r, float zNear, float P00, float P11, out vec4 aabb) {
    if (-C.z - r < zNear) {
        return false;
    }

    if (cameraData.isOrtho == 1) {
        const float left   = cameraData.orthoBounds.x;
        const float right  = cameraData.orthoBounds.y;
        const float bottom = cameraData.orthoBounds.z;
        const float top    = cameraData.orthoBounds.w;

        vec2 cMin = C.xy - vec2(r);
        vec2 cMax = C.xy + vec2(r);

        float x = (2.0 * cMin.x - (right + left)) / (right - left);
        float y = (2.0 * cMin.y - (top + bottom)) / (top - bottom);
        float z = (2.0 * cMax.x - (right + left)) / (right - left);
        float w = (2.0 * cMax.y - (top + bottom)) / (top - bottom);
        aabb = vec4(x, y, z, w);
        aabb = aabb * 0.5 + 0.5;// clip space -> uv space
    } else {
        P11 = -P11;

        vec2 cx = -C.xz;
        vec2 vx = vec2(sqrt(dot(cx, cx) - r * r), r);
        vec2 minx = mat2(vx.x, vx.y, -vx.y, vx.x) * cx;
        vec2 maxx = mat2(vx.x, -vx.y, vx.y, vx.x) * cx;

        vec2 cy = -C.yz;
        vec2 vy = vec2(sqrt(dot(cy, cy) - r * r), r);
        vec2 miny = mat2(vy.x, vy.y, -vy.y, vy.x) * cy;
        vec2 maxy = mat2(vy.x, -vy.y, vy.y, vy.x) * cy;

        aabb = vec4(minx.x / minx.y * P00, miny.x / miny.y * P11, maxx.x / maxx.y * P00, maxy.x / maxy.y * P11);
        aabb = vec4(0.5f, 0.5f, 0.5f, 0.5f) - vec4(0.5f, 0.5f, 0.5f, 0.5f) * aabb;// clip space -> uv space

        // Vulkan uv -> OpenGL uv
        aabb = vec4(aabb.z, 1.0f - aabb.w, aabb.x, 1.0f - aabb.y);

        // {
        //     aabb = vec4(minx.x / minx.y * P00, maxy.x / maxy.y * P11, maxx.x / maxx.y * P00, miny.x / miny.y * P11);
        //     aabb = vec4(0.5f) + aabb * vec2(-0.5f, 0.5f).xyxy;
        // }
    }
    return true;
}

int GetMipLevelFromAABB(vec4 aabb, int desiredFootprintPixels) {
    vec2 hzbSize = vec2(cullData.hzbWidth, cullData.hzbHeight);
    ivec4 aabbPixels = ivec4(aabb * hzbSize.xyxy + vec4(0.5f, 0.5f, -0.5f, -0.5f));

    const int maxPixelOffset = desiredFootprintPixels - 1;
    const int mipOffset = int(log2(float(desiredFootprintPixels))) - 1;

    // Calculate lowest mip level that allows us to cover footprint of the desired size in pixels.
    // Start by calculating separate x and y mip level requirements.
    // 2 pixels of mip k cover 2^(k+1) pixels of mip 0. To cover at least n pixels of mip 0 by two pixels of mip k we need k to be at least k = ceil( log2( n ) ) - 1.
    // For integer n>1: ceil( log2( n ) ) = floor( log2( n - 1 ) ) + 1.
    // So k = floor( log2( n - 1 )
    // For integer n>1: floor( log2( n ) ) = findMSB( n )
    // So k = findMSB( n - 1 )
    // As aabbPixels min/max are both inclusive their difference is one less than number of pixels (n - 1), so applying findMSB to this difference gives the minimum required mip.
    // NOTE: findMSB(firstbithigh) is a FULL rate instruction on GCN while log2 is QUARTER rate instruction.
    ivec2 mipLevelXY = ivec2(findMSB(aabbPixels.z - aabbPixels.x), findMSB(aabbPixels.w - aabbPixels.y));

    // Mip level needs to be big enough to cover both x and y requirements. Go one extra level down for 4x4 sampling.
    // findMSB(0) = -1, so clamping with 0 here also handles the n=1 case where mip 0 footprint is just 1 pixel wide/tall.
    int mipLevel = max(max(mipLevelXY.x, mipLevelXY.y) - mipOffset, 0);

    // MipLevel now contains the minimum MipLevel that can cover a number of pixels equal to the size of the rectangle footprint, but the HZB footprint alignments are quantized to powers of two.
    // The quantization can translate down the start of the represented range by up to 2^k-1 pixels, which can decrease the number of usable pixels down to 2^(k+1) - 2^k-1.
    // Depending on the alignment of the rectangle this might require us to pick one level higher to cover all rectangle footprint pixels.
    // Note that testing one level higher is always enough as this guarantees 2^(k+2) - 2^k usable pixels after alignment, which is more than the 2^(k+1) required pixels.

    // Transform coordinates down to coordinates of selected mip level and if they are not within reach increase level by one.
    ivec2 mipLevelAdjustedSize = (aabbPixels.zw >> mipLevel) - (aabbPixels.xy >> mipLevel);
    mipLevel += (mipLevelAdjustedSize.x > maxPixelOffset || mipLevelAdjustedSize.y > maxPixelOffset) ? 1 : 0;

    return mipLevel;

    //    vec2 hzbSize = vec2(cullData.hzbWidth, cullData.hzbHeight);
    //    float width = (aabb.z - aabb.x) * hzbSize.x;
    //    float height = (aabb.w - aabb.y) * hzbSize.y;
    //
    //    // Calculate lowest mip level that allows us to cover footprint of the desired size in pixels.
    //    // Start by calculating separate x and y mip level requirements.
    //    // 2 pixels of mip k cover 2^(k+1) pixels of mip 0. To cover at least n pixels of mip 0 by two pixels of mip k we need k to be at least k = ceil( log2( n ) ) - 1.
    //    // For integer n>1: ceil( log2( n ) ) = floor( log2( n - 1 ) ) + 1.
    //    // So k = floor( log2( n - 1 )
    //    const int mipOffset = int(log2(float(desiredFootprintPixels))) - 1;
    //
    //    float n = max(width, height);
    //    int k = int(floor(log2(n - 1)));
    //    int mipLevel = max(k - mipOffset, 0);
    //
    //    return mipLevel;
}

float GetMinDepthFromHZB(vec4 aabb, bool bSample4x4) {
    float minDepth = 1.0f;

    if (bSample4x4) {
        float level = float(GetMipLevelFromAABB(aabb, 4));

        vec2 minCoord = aabb.xy;
        vec2 maxCoord = aabb.zw;

        vec2 stepSize = (maxCoord - minCoord) / 3.0f;

        for (uint y = 0; y < 4; ++y) {
            for (uint x = 0; x < 4; ++x) {
                vec2 sampleCoord = minCoord + vec2(x, y) * stepSize;
                float depth = textureLod(hzbSampler, sampleCoord, level).r;
                minDepth = min(minDepth, depth);
            }
        }
    } else {
        float level = float(GetMipLevelFromAABB(aabb, 2));

        float depth_0 = textureLod(hzbSampler, aabb.xy, level).r;
        float depth_1 = textureLod(hzbSampler, aabb.xw, level).r;
        float depth_2 = textureLod(hzbSampler, aabb.zw, level).r;
        float depth_3 = textureLod(hzbSampler, aabb.zy, level).r;

        minDepth = min(min(depth_0, depth_1), min(depth_2, depth_3));
    }

    // float epsilon = 1e-7;
    // minDepth -= epsilon;

    return minDepth;
}

// Function to perform occlusion culling
bool IsVisible(MeshletDescriptor meshletDescriptor) {
    vec4 sphereBounds = meshletDescriptor.spherebounds;

    // in the right-handed coordinate system, the z value of the view coordinate is negative
    vec3 center = sphereBounds.xyz;
    center = (cullData.view_model * vec4(center, 1.0f)).xyz;
    float radius = sphereBounds.w;

    bool visible = true;

    // the left/top/right/bottom plane culling utilizes frustum symmetry to cull against two planes at the same time
    if (visible) {
        if (cameraData.isOrtho == 1) {
            const float left   = cameraData.orthoBounds.x;
            const float right  = cameraData.orthoBounds.y;
            const float bottom = cameraData.orthoBounds.z;
            const float top    = cameraData.orthoBounds.w;

            visible = visible && (center.x + radius > left && center.x - radius < right);
            visible = visible && (center.y + radius > bottom && center.y - radius < top);
        } else {
            visible = visible && center.z * cullData.frustum[1] - abs(center.x) * cullData.frustum[0] > -radius;
            visible = visible && center.z * cullData.frustum[3] - abs(center.y) * cullData.frustum[2] > -radius;
        }
    }

    // dist culling
    //    if (visible) {
    //        visible = visible && -center.z + radius > cullData.zNear && -center.z - radius < cullData.zFar;
    //    }

    vec4 aabb;
    bool projected = ProjectSphere(center, radius, cullData.zNear, cullData.P00, cullData.P11, aabb);

    // small meshlet culling(less than one pixel)
    //    if (visible && projected) {
    //        const vec2 minScreenPosition = aabb.xy * vec2(cullData.hzbWidth, cullData.hzbHeight);
    //        const vec2 maxScreenPosition = aabb.zw * vec2(cullData.hzbWidth, cullData.hzbHeight);
    //        visible = visible && !any(round(minScreenPosition) == round(maxScreenPosition));
    //    }

    // occlusion culling
    if (visible && projected) {
        float depth = GetMinDepthFromHZB(aabb, true);

        float z = center.z + radius;// From the camera's perspective, z is negative.

        float depthSphere;
        if (cameraData.isOrtho == 1) {
            depthSphere = (z + cullData.zFar) / (cullData.zFar - cullData.zNear);
        } else {
            // Unlimited viewing distance
            // float depthSphere = cullData.zNear / -z;

            // Limited viewing distance
            float n = cullData.zNear;
            float f = cullData.zFar;
            depthSphere = (n + n * f / z) / (n - f);
        }

        visible = visible && depthSphere >= depth;
    }

    return visible;
}
